<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getAllPosts($page, $rows_per_page)
    {
        $offset = 0;
        if ($page > 1)
        {
            $offset = $rows_per_page * ($page-1);
        }
        $dql = "SELECT p FROM AppBundle:User p ORDER BY p.id DESC ";
        $query = $this->getEntityManager()->createQuery($dql)
            ->setFirstResult($offset)
            ->setMaxResults($rows_per_page);
        
        return $query;
    }
    public function sortByUser($page, $rows_per_page, $order_d='DESC')
    {
        $offset = 0;

        if ($page > 1)
        {
            $offset = $rows_per_page * ($page-1);
        }
        if (strcasecmp($order_d,'DESC') == 0)
        {
            $dql = "SELECT p FROM AppBundle:User p ORDER BY p.name DESC";

        }else{

            $dql = "SELECT p FROM AppBundle:User p ORDER BY p.name ASC";
            
        }

        $query = $this->getEntityManager()->createQuery($dql)
            ->setFirstResult($offset)
            ->setMaxResults($rows_per_page);
  
        return $query;
    }
    public function sortByDate($page, $rows_per_page, $order_d='DESC')
    {
        $offset = 0;
        if ($page > 1)
        {
            $offset = $rows_per_page * ($page-1);
        }
        if (strcasecmp($order_d,'DESC') == 0)
        {
            $dql = "SELECT p FROM AppBundle:User p ORDER BY p.createdAt DESC";
        }else{

            $dql = "SELECT p FROM AppBundle:User p ORDER BY p.createdAt ASC";
        }

        $query = $this->getEntityManager()->createQuery($dql)
            ->setFirstResult($offset)
            ->setMaxResults($rows_per_page);

        return $query;
    }

    public function sortByEmail($page, $rows_per_page, $order_d='DESC')
    {
        $offset = 0;
        if ($page > 1)
        {
            $offset = $rows_per_page * ($page-1);
        }
        if (strcasecmp($order_d,'DESC') == 0)
        {
            $dql = "SELECT p FROM AppBundle:User p ORDER BY p.email DESC";
        }else{

            $dql = "SELECT p FROM AppBundle:User p ORDER BY p.email ASC";
        }

        $query = $this->getEntityManager()->createQuery($dql)
            ->setFirstResult($offset)
            ->setMaxResults($rows_per_page);

        return $query;
    }

}
